# Generated by Django 3.0.6 on 2020-06-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
                ('emailAddress', models.EmailField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
