# Generated by Django 3.0.6 on 2020-06-09 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='your_message',
            field=models.TextField(default=datetime.datetime(2020, 6, 9, 3, 29, 8, 199887, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
